Update schema id URL from NABSA to MobilityData repo
MobilityData/gbfs-validator pull request #158
Opened 2023-11-21 20:02 UTC by richfab

Fixes https://github.com/MobilityData/gbfs-json-schema/issues/101

This PR updates the schema id URLs from NABSA to MobilityData repo and fixes the anchors:

Before | After
-- | --
`"https://github.com/NABSA/gbfs/blob/v3.0-RC/gbfs.md#vehicle_typesjson-added-in-v21-rc"`, | `"https://github.com/MobilityData/gbfs/blob/v3.0-RC/gbfs.md#vehicle_typesjson"`~~-added-in-v21-rc~~,

2023-11-22 14:49 UTC, davidgamez requested changes
There are a few additions of uniqueness in an array that are out of the scope of this PR. Please consider creating a separate PR for those changes.

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v3.0-RC2/vehicle_types.json
> +                "uniqueItems": true,
This is out of the scope of this PR.

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v3.0-RC2/system_alerts.json
> +                "uniqueItems": true,
This is out of the scope of this PR.

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v3.0-RC2/station_status.json
> +                      "uniqueItems": true,
This is out of the scope of this PR.

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v3.0-RC2/station_information.json
> +                      "uniqueItems": true,
This is out of the scope of this PR.

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v3.0-RC2/geofencing_zones.json
> +                "uniqueItems": true,
This is out of the scope of this PR.

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v3.0-RC/vehicle_types.json
> +                "uniqueItems": true,
This is out of the scope of this PR.

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v3.0-RC/system_alerts.json
> +                "uniqueItems": true,
This is out of the scope of this PR.

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v3.0-RC/station_status.json
> +                      "uniqueItems": true,
This is out of the scope of this PR.

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v3.0-RC/geofencing_zones.json
> +                              "uniqueItems": true,
This is out of the scope of this PR.

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v2.3/vehicle_types.json
> +                "uniqueItems": true,
👁️

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v2.3/system_alerts.json
> +                "uniqueItems": true,
👁️

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v2.3/station_status.json
> +                      "uniqueItems": true,
👁️

2023-11-22 14:49 UTC, davidgamez commented on gbfs-validator/versions/schemas/v2.0/system_alerts.json
> +                "uniqueItems": true,
This is out of the scope of this PR and affects previously released versions.

2023-11-22 17:03 UTC, richfab commented
Good catch @davidgamez! I created this separate PR: https://github.com/MobilityData/gbfs-validator/pull/159

2023-12-04 20:05 UTC, davidgamez approved these changes
LGTM!

2023-12-05 10:45 UTC, merged